spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ29lWWhQR0J4NmtlbVcxWlcKdnU5d2Y3ZGxJdGw5OFB4ci9GN2lnT3ZjZUR1aFJBTkNBQVNORjFFNjVmNENmd0xpNG4rbUMzQ1pkeXVDQ3N5Wgo1RU1qSXJDMW9vUVdoalJnb3RnQnJOdFVkbjBINmJsV0lOaGRYNnpRc0NLYndtbENPWjNCSHlBYgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNUakNDQWZXZ0F3SUJBZ0lRZlZGdUNYako4ZE5VV3JTNTVkclluREFLQmdncWhrak9QUVFEQWpDQmp6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1USXdNQVlEVlFRTERDbHZkV0ZqYUdGdQphVUJ2ZFdGamFHRnVhUzFXVFhkaGNtVXRWbWx5ZEhWaGJDMVFiR0YwWm05eWJURTVNRGNHQTFVRUF3d3diV3RqClpYSjBJRzkxWVdOb1lXNXBRRzkxWVdOb1lXNXBMVlpOZDJGeVpTMVdhWEowZFdGc0xWQnNZWFJtYjNKdE1CNFgKRFRJMk1EUXhOVEE1TVRjeE0xb1hEVEk0TURjeE5UQTVNVGN4TTFvd1hURW5NQ1VHQTFVRUNoTWViV3RqWlhKMApJR1JsZG1Wc2IzQnRaVzUwSUdObGNuUnBabWxqWVhSbE1USXdNQVlEVlFRTERDbHZkV0ZqYUdGdWFVQnZkV0ZqCmFHRnVhUzFXVFhkaGNtVXRWbWx5ZEhWaGJDMVFiR0YwWm05eWJUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDkKQXdFSEEwSUFCSTBYVVRybC9nSi9BdUxpZjZZTGNKbDNLNElLekpua1F5TWlzTFdpaEJhR05HQ2kyQUdzMjFSMgpmUWZwdVZZZzJGMWZyTkN3SXB2Q2FVSTVuY0VmSUJ1alpEQmlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WCkhTVUVEREFLQmdnckJnRUZCUWNEQVRBZkJnTlZIU01FR0RBV2dCVDc2NW13eHcxeTdhR3BxbGFlUjNpYzFobWEKSWpBYUJnTlZIUkVFRXpBUmdnOXNiMk5oYkM0d2VHUmlaUzVrWlhZd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZwpNeWFDeUIySExFaVpTc0o3Y0NoYVA5a0I1bmdINGt3d3Nhek1wT1VqcUZJQ0lCc000MTMzOW9Kd0dwSlBZZ203CnRjUmhzU1hEUmd6OWUzSEdQSXRXdS9hcgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
          trustore:
            certification: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNaVENDQWdxZ0F3SUJBZ0lSQUxBYWNtTFNMdHFXVkFjTnNoai84bm93Q2dZSUtvWkl6ajBFQXdJd2dZOHgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURXlNREFHQTFVRUN3d3BiM1ZoWTJoaApibWxBYjNWaFkyaGhibWt0VmsxM1lYSmxMVlpwY25SMVlXd3RVR3hoZEdadmNtMHhPVEEzQmdOVkJBTU1NRzFyClkyVnlkQ0J2ZFdGamFHRnVhVUJ2ZFdGamFHRnVhUzFXVFhkaGNtVXRWbWx5ZEhWaGJDMVFiR0YwWm05eWJUQWUKRncweU5qQTBNVFV3T1RFeU1qVmFGdzB6TmpBME1UVXdPVEV5TWpWYU1JR1BNUjR3SEFZRFZRUUtFeFZ0YTJObApjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhNakF3QmdOVkJBc01LVzkxWVdOb1lXNXBRRzkxWVdOb1lXNXBMVlpOCmQyRnlaUzFXYVhKMGRXRnNMVkJzWVhSbWIzSnRNVGt3TndZRFZRUUREREJ0YTJObGNuUWdiM1ZoWTJoaGJtbEEKYjNWaFkyaGhibWt0VmsxM1lYSmxMVlpwY25SMVlXd3RVR3hoZEdadmNtMHdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVJXZFB0U3ZxRE90VjVTN3ozYkdIOGdYV3pyRmNuU3k5TmhqYitUZTFZVVRpZzRnZDRpCkRDK1Z1b1R1bTJGRXRJcGdqeU1IOHlkR0l1RysyUzFmNFlUc28wVXdRekFPQmdOVkhROEJBZjhFQkFNQ0FnUXcKRWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQURBZEJnTlZIUTRFRmdRVSsrdVpzTWNOY3UyaHFhcFdua2Q0bk5ZWgptaUl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUw5SjZNQVlBOU9ZSVhMN3pxbkJYdTJ5dE5uQjdMV20zYkJsCkRLN05QK3N0QWlFQXp4NzN2SktPZkxMNnE0VzZmeEp2L1l0aCtkL04vV2NqVlI2bGtVTGcxYWs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"  

  # Step 1a: Configure SSL with the certificate and private key
  # ...
  # Step 1a: End of SSL configuration

server:
  port: 8443
  ssl:
    Bundle : web
  # Step 1b: Enable SSL and specify ssl bundle
  # ...
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  # ...
  servlet:
    session:
      cookie:
        same-site: STRICT
  # Step 5: End of session cookie configuration