name: security
on:
  workflow_dispatch:

permissions:
  # Required to upload SARIF file to CodeQL.
  actions: read
  # Require writing security events to upload SARIF file
  security-events: write
  # to fetch code (actions/checkout)
  contents: read

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@main
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Upload OSV report to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysisFull.sarif

  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run analysis with semgrep
        run: semgrep scan --config .semgrep --sarif --output SourceCodeAnalysis.sarif
        continue-on-error: true

      - name: Upload Semgrep report to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: SourceCodeAnalysis.sarif
